# Generated by Django 2.0.2 on 2018-02-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=12)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PairWise.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('size', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='PairWise.CourseSection')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_search', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PairWise.CourseSection')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSection',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('pass_salt', models.CharField(max_length=16)),
                ('pass_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='searches',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PairWise.User'),
        ),
        migrations.AddField(
            model_name='results',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_id', to='PairWise.User'),
        ),
        migrations.AddField(
            model_name='results',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PairWise.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='PairWise.User'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='times',
            field=models.ManyToManyField(to='PairWise.TimeSection'),
        ),
    ]
